test_data = {
    "id": 12,
    "SubmissionDate": "11/11/14 2:57",
    "SubmissionDateSIF": "11/11/14 2:57",
    "times_visited": 1,
    "RE": "Brhane-GMariam",
    "region": "Tigray",
    "zone": "z0101",
    "district": "d010101",
    "locality": "L0101013001",
    "EArandom": 3577,
    "EA": "L0101013001_ea06",
    "facility_number": 2,
    "facility_type": "health_center",
    "advanced_facility": "yes",
    "managing_authority": "government",
    "available": "yes",
    "consent_obtained": 1,
    "facility_name": "Adi Hageray Health Center",
    "position": "In-Charge/Manager",
    "year_open": "1-Jan-20",
    "year_openSIF": "1/1/20 0:00",
    "days_open": 6,
    "staffing_doctor_tot": 0,
    "staffing_doctor_here": 0,
    "staffing_nurse_tot": 14,
    "staffing_nurse_here": 14,
    "staffing_ho_tot": 1,
    "staffing_ho_here": 1,
    "staffing_ambulance_tot": 0,
    "staffing_ambulance_here": 0,
    "staffing_pharmacist_tot": 2,
    "staffing_pharmacist_here": 2,
    "staffing_mca_tot": 0,
    "staffing_mca_here": 0,
    "staffing_other_tot": 2,
    "staffing_other_here": 2,
    "present_24hr": "yes",
    "knows_population_served": "yes_knows_size",
    "population_served": 30000,
    "beds": 15,
    "supervisor_visit": "past_6mo",
    "electricity": "yes",
    "water": "yes",
    "handwashing_stations": 3,
    "handwashing_observations": "soap stored_water tap_water near_sanitation",
    "soap_present": 1,
    "stored_water_present": 1,
    "running_water_present": 1,
    "near_sanitation": 1,
    "computer": "yes",
    "sharps": "burn_incinerator",
    "fp_offered": "yes",
    "fp_begin": "1-Jan-20",
    "fp_beginSIF": "1/1/20 0:00",
    "fp_days": 5,
    "fp_today": "yes",
    "fp_community_health_volunteers": "yes",
    "community_health_volunteers": 185,
    "methods_offered": -77,
    "chv_condoms": "no",
    "chv_pills": "no",
    "chv_injectables": "no",
    "mobile_outreach": 0,
    "fees": "no",
    "fees_posted": "",
    "opinions_collected": "box interview",
    "opinion_box": "yes",
    "opinion_survey": "no",
    "opinion_interview": "yes",
    "opinion_meeting": "no",
    "opinion_informal": "no",
    "opinion_direct": "no",
    "opinion_other": "no",
    "opinions_reported": "yes",
    "opinions_observed": "report_not_seen",
    "opinion_action": "yes_change_in_comfort",
    "opinion_no_change": "no",
    "opinion_change_in_service": "no",
    "opinion_change_in_comfort": "yes",
    "opinion_change_other": "no",
    "service_stats": "yes",
    "stats_analyzed": "chart",
    "reports_wall_chart": "yes",
    "reports_written": "no",
    "reports_other": "no",
    "reports_nothing": "no",
    "offered_female_ster": "counseled prescribed",
    "offered_male_ster": "counseled prescribed",
    "offered_implants": "counseled provided",
    "offered_iud": "counseled provided",
    "offered_injectables": "counseled provided",
    "offered_pills": "counseled provided",
    "offered_progestin_pill": "counseled provided",
    "offered_male_condom": "counseled provided",
    "offered_female_condom": "",
    "offered_ec": "counseled provided",
    "offered_beads": "",
    "offered_lam": "",
    "offered_rhythm": "",
    "offered_withdrawal": "",
    "counseled_female_ster": "yes",
    "counseled_male_ster": "yes",
    "counseled_implants": "yes",
    "counseled_iud": "yes",
    "counseled_injectables": "yes",
    "counseled_progestin": "yes",
    "counseled_pills": "yes",
    "counseled_male_condom": "yes",
    "counseled_female_condom": "",
    "counseled_ec": "yes",
    "counseled_beads": "",
    "counseled_lam": "",
    "counseled_rhythm": "",
    "counseled_withdrawal": "",
    "provided_female_ster": "no",
    "provided_male_ster": "no",
    "provided_implants": "yes",
    "provided_iud": "yes",
    "provided_injectables": "yes",
    "provided_progestin": "yes",
    "provided_pills": "yes",
    "provided_male_condom": "yes",
    "provided_female_condom": "",
    "provided_ec": "yes",
    "provided_beads": "",
    "prescribed_female_ster": "yes",
    "prescribed_male_ster": "yes",
    "prescribed_implants": "no",
    "prescribed_iud": "no",
    "prescribed_injectables": "no",
    "prescribed_progestin": "no",
    "prescribed_pills": "no",
    "prescribed_male_condom": "no",
    "prescribed_female_condom": "",
    "prescribed_ec": "no",
    "prescribed_beads": "",
    "charged_female_ster": "no",
    "charged_male_ster": "no",
    "charged_implants": "no",
    "charged_iud": "no",
    "charged_injectables": "no",
    "charged_progestin": "no",
    "charged_pills": "no",
    "charged_male_condom": "no",
    "charged_female_condom": "",
    "charged_ec": "no",
    "charged_beads": "",
    "fees_female_ster": "",
    "fees_male_ster": "",
    "fees_implants": "",
    "fees_iud": "",
    "fees_injectables": "",
    "fees_pills": "",
    "fees_progestin": "",
    "fees_male_condom": "",
    "fees_female_condom": "",
    "fees_ec": "",
    "fees_beads": "",
    "implant_insert": "yes",
    "implant_remove": "yes",
    "iud_insert": "yes",
    "iud_remove": "yes",
    "implant_supplies": "clean-gloves antiseptic sterile-gauze-pad-or-cotton-wool local-anesthetic sealed-implant-pack blade",
    "implant_gloves": "yes",
    "implant_antiseptic": "yes",
    "implant_sterile_gauze": "yes",
    "implant_anesthetic": "yes",
    "implant_sealed_pack": "yes",
    "implant_blade": "yes",
    "iud_supplies": "sponge-holding-forceps speculums tenaculum clamp",
    "iud_forceps": "yes",
    "iud_speculums": "yes",
    "iud_tenaculum": "yes",
    "iud_clamp": "yes",
    "visits_female_ster": "",
    "visits_male_ster": "",
    "visits_implants_total": 100,
    "visits_implants_new": 20,
    "visits_iud_total": 0,
    "visits_iud_new": 0,
    "visits_progestin_total": 11,
    "visits_progestin_new": 11,
    "visits_injectables_total": 140,
    "visits_injectables_new": 20,
    "visits_pills_total": 0,
    "visits_pills_new": 0,
    "visits_male_condom_total": 0,
    "visits_male_condom_new": 0,
    "visits_female_condom_total": "",
    "visits_female_condom_new": "",
    "visits_ec_total": 0,
    "visits_ec_new": 0,
    "visits_beads_total": "",
    "visits_beads_new": "",
    "sold_implants": "",
    "sold_iud": "",
    "sold_injectables": "",
    "sold_progestin": "",
    "sold_pills": "",
    "sold_male_condoms": "",
    "sold_female_condoms": "",
    "sold_ec": "",
    "sold_beads": "",
    "maternalservices": "antenatal delivery postnatal postabortion",
    "antenatal": "yes",
    "delivery": "yes",
    "postnatal": "yes",
    "post_abortion": "yes",
    "postpartum": "diet mental fertility healthy_spacing",
    "postpartum_diet": "yes",
    "postpartum_mental": "yes",
    "postpartum_fertility": "yes",
    "postpartum_healthy_spacing": "yes",
    "postpartum_lam": "no",
    "postpartum_long_acting_fp": "no",
    "postpartum_spacing": "no",
    "fp_during_postpartum": "yes",
    "postabortion_discussion": "mental fertility healthy_spacing long_acting FP_methods_spacing",
    "postabortion_mental": "yes",
    "postabortion_fertility": "yes",
    "postabortion_healthy_spacing": "yes",
    "postabortion_long_acting_fp": "yes",
    "postabortion_spacing": "yes",
    "fp_during_postabortion": "yes",
    "adolescents": "counseled provided",
    "adolescents_counseled": "yes",
    "adolescents_provided": "yes",
    "adolescents_prescribed": "no",
    "hiv_services": "yes",
    "sti_services": "yes",
    "hiv_fp": "counseled provided",
    "hiv_fp_counseled": "yes",
    "hiv_fp_provided": "yes",
    "hiv_fp_prescribed": "no",
    "hiv_consultation_intentions": "yes",
    "hiv_consultation_method": "yes",
    "hiv_consultation_dual_method": "yes",
    "hiv_consultation_condoms": "yes",
    "hiv_consultation_instructions": "yes",
    "hiv_consultation_fp": "yes",
    "exam_room_piped_water": "observed",
    "exam_room_other_running_water": "observed",
    "exam_room_bucket_water": "observed",
    "exam_room_soap": "observed",
    "exam_room_towels": "reported_unseen",
    "exam_room_wastebin": "observed",
    "exam_room_sharps": "observed",
    "exam_room_latex_gloves": "reported_unseen",
    "exam_room_disinfectant": "observed",
    "exam_room_needles": "observed",
    "exam_room_auditory_privacy": "observed",
    "exam_room_visual_privacy": "observed",
    "exam_room_tables": "observed",
    "exam_room_ed_materials": "observed",
    "fp_room_conditions_floor": "yes",
    "fp_room_conditions_tables": "yes",
    "fp_room_conditions_equipment": "yes",
    "fp_room_conditions_doors": "yes",
    "fp_room_conditions_walls": 2,
    "fp_room_conditions_roof": 2,
    "fp_room_conditions_wallsc": 2,
    "stock_implants": "instock_obs",
    "stockout_days_implants": "",
    "stockout_3mo_implants": "no",
    "stock_iud": "instock_obs",
    "stockout_days_iud": "",
    "stockout_3mo_iud": "no",
    "stock_injectables": "instock_obs",
    "stockout_days_injectables": "",
    "stockout_3mo_injectables": "no",
    "stock_pills": "instock_obs",
    "stockout_days_pills": "",
    "stockout_3mo_pills": "no",
    "stock_progestin": "instock_obs",
    "stockout_days_progestin": "",
    "stockout_3mo_progestin": "yes",
    "stock_male_condoms": "instock_obs",
    "stockout_days_male_condoms": "",
    "stockout_3mo_male_condoms": "yes",
    "stock_female_condoms": "",
    "stockout_days_female_condoms": "",
    "stockout_3mo_female_condoms": "",
    "stock_ec": "instock_obs",
    "stockout_days_ec": "",
    "stockout_3mo_ec": "yes",
    "stock_beads": "",
    "stockout_days_beads": "",
    "stockout_3mo_beads": "",
    "protected_floor": "yes",
    "protected_water": "yes",
    "protected_sun": "yes",
    "protected_pests": "yes",
    "locationlatitude": 14.45626831,
    "locationlongitude": 37.98556137,
    "locationaltitude": 1499.800049,
    "locationaccuracy": 4.5,
    "SDP_result": "completed",
    "start": "10/23/14 3:14",
    "startSIF": "10/23/14 3:14",
    "end": "10/23/14 5:41",
    "endSIF": "10/23/14 5:41",
    "metainstanceID": "uuid:8b461bbb-94b9-4234-aed3-199a69c3e438",
    "metainstancename": "SDP:L0101013001-2",
    "RErandom": 2526,
    "facility_type_v2": "health_center",
    "sector": "Public",
    "offer_stock_iud": "In stock",
    "offer_stock_implants": "In stock",
    "offer_stock_injectables": "In stock",
    "offer_stock_pills": "In stock",
    "offer_stock_male_condoms": "In stock",
    "offer_stock3_iud": "In stock",
    "offer_stock3_implants": "In stock",
    "offer_stock3_injectables": "In stock",
    "offer_stock3_pills": "In stock",
    "offer_stock3_male_condoms": "Out of stock in last 3 months",
    "available_iud": "Yes",
    "available_implants": "Yes",
    "available_injectables": "Yes",
    "available_pills": "Yes",
    "available_progestin": "Yes",
    "available_male_condom": "Yes",
    "available_female_condom": "No",
    "available_ec": "Yes",
    "available_beads": "No",
    "total_methods_available": 7,
    "threshold_3": "Yes",
    "threshold_5": "Yes",
    "fp_days_mean": 5.426035404,
    "fp_days_mean_total": 5.52072525,
    "adfp": "Yes",
    "chws": "Yes",
    "mobile_outreach_2": "No",
    "mhsoffer": "Yes",
    "fpmhs": "Yes",
    "fphiv": "Yes",
    "fppa": "Yes",
    "Probabilityofselection": 0.01231097,
    "FQweight": 0.330562741,
    "EAtag": 1,
    "EAweight": 0.197174922,
    "_merge": "matched (3)"
}
